
---
- name: Copiar y subir informe al repositorio
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
     fecha_actual: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}" #formato fecha
     nombre_archivo: "InformeIdiger_{{ fecha_actual }}.html"
     ruta_destino: "/var/lib/awx/projects/_6__dbsystem_piloto_git/Ansible/ResultadosInformes/{{ nombre_archivo }}"

  tasks:
    - name: Copiar archivo a repositorio
      copy:
        src: "/tmp/InformeDiagnosticoIdiger.html"
        dest: "{{ ruta_destino }}"
        mode: '0644'
      delegate_to: localhost
      run_once: true
      tags: copiarArchivo

    - name: Hacer commit y push
      shell: |
        cd /var/lib/awx/projects/_6__awx_pruebas/Ansible/ResultadosInformes/
        git config --global user.name "AWX"
        git config --global user.email "awx@localhost"
        git add .
        git commit -m "Informe sistema {{ fecha_actual }}"
        git push origin main
      delegate_to: localhost
      run_once: true
      tags: cargaArhivo

    - name: Eliminar archivo local
      file:
        path: "/tmp/InformeDiagnosticoIdiger.html"
        state: absent
      delegate_to: localhost
      run_once: true
      tags: limpiarLocal
      
    - name: Eliminar archivo temporal
      file:
        path: "/tmp/informesTemporal.txt"
        state: absent
      delegate_to: localhost
      run_once: true
      tags: limpiarTemporal

