

---
- name: Informe Diagnostico

  hosts: "{{ groups['Actualizacion'] | sort }}"

  become: true

  gather_facts: false

  order: sorted  # Orden alfabetico numerico

  serial: 1

  vars:
    fecha_actual: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    ruta_html: "/tmp/InformeDiagnosticoIdiger.html"
    
  tasks:

    - name: Obtener informacion del sistema operativo
  
      command: hostnamectl
     
      register: host_info 
     
      tags: hostname

    - name: Extraer informacion de Host
      set_fact:
              hostname: "{{ host_info.stdout_lines | select('search', 'Static hostname') | first | regex_replace('.*:\\s+', '')}}"
              virtualization: "{{ host_info.stdout_lines | select('search', 'Virtualization') | first | regex_replace('.*:\\s+', '')}}"
              operaSystem: "{{ host_info.stdout_lines | select('search', 'Operating System') | first | regex_replace('.*:\\s+', '')}}"
              kernel: "{{ host_info.stdout_lines | select('search', 'Kernel') | first | regex_replace('.*:\\s+', '')}}"
              architecture: "{{ host_info.stdout_lines | select('search', 'Architecture') | first | regex_replace('.*:\\s+', '')}}"

      tags: hostnameE

    - name: Informacion memoria
      shell: |
        echo "=== Informacion de memoria ==="
        free -hm

      register: mem_info

      tags: memInfo

    - name: Verificar uso de memoria
      shell: |
              result=$(awk '
              /MemTotal/ {total=$2}
              /MemAvailable/ {available=$2}
              /SwapTotal/ {swaptotal=$2}
              /SwapFree/ {swapfree=$2}
              END {
                      used_ram = total - available;
                      percent_ram = (used_ram/total)*100;

                      if (percent_ram > 85) {
                              printf "Alerta RAM: %.1f%% usada\n", percent_ram
                      }
                      if (swaptotal > 85) {
                              used_swap = swaptotal - swapfree;
                              percent_swap = (used_swap/swaptotal)*100;
                              if (percent_swap > 85){
                                      printf "Alerta Swap: %.1f%% usada\n", percent_swap
                              }
                      }
              }' /proc/meminfo)
              if [ -n "$result" ]; then
              echo "Memoria No okey"
              echo "$result"
              else
              echo "Memoria okey" 
              fi
      register: mem_status
      tags: memPorcentaje


    - name: Verificar uso de disco
      shell: |
              result=$(df -hT | awk 'NR>1 && $6+0 > 85 {
              
                      print " ALERTA: " $1 " esta al " $6 " de uso"
                      
                      print " Tipo: " $2 " | Montado en: " $7
                      
                      print " Tamaño: " $3 " | Usado: " $4 " | Libre: " $5 

                      print " ---------------------------------------"
              
              }')
              if [ -n "$result" ]; then 
              echo "Se reportan los siguientes fylesystems que superan el umbral del 85%"

              echo "$result"
              else
              echo "Correcto Todos los fylesystems estan por debajo del 85%"
              fi
      
      register: fs_status

      tags: discoIn

    - name: Obtener informacion de Networking
      shell: |
         nmcli -f GENERAL.DEVICE,GENERAL.TYPE,GENERAL.STATE,IP4.ADDRESS device show

      register: infoNet

      tags: ipInfo

    - name:  Informacion actualizaciones de seguridad
      shell: dnf updateinfo list updates --security

      register: info_security

      changed_when: false

      tags: infoSecurity

    - name: Aplicar actualizaciones de seguridad
      shell: |
        dnf update --security -y
      register: security_update
      ignore_errors: yes
      when: info_security.stdout | length > 0
      tags: aplicarActualizacion

    - name: Limpiar cache reintento
      shell: |
        dnf clean all
        dnf makecache
        dnf update --security -y
      register: security_cache
      when:
        - info_security.stdout | length > 0
        - security_update is failed
      tags: reintentarCache

    - name: Crear reporte individual
      set_fact:
        reporte_host: |
                <div class="host-block">
                <h2>Host: {{ hostname }}</h2>
                <ul>
                  <li><b>Virtualización:</b> {{ virtualization }}</li>
                  <li><b>Sistema Operativo:</b> {{ operaSystem }}</li>
                  <li><b>Kernel:</b> {{ kernel }}</li>
                  <li><b>Arquitectura:</b> {{ architecture }}</li>
                </ul>
                
                <h3>Información Memoria</h3>
                <pre>{{ mem_info.stdout }}</pre>
                <p>{{ mem_status.stdout }}</p>
                
                <h3>Información espacio Disco</h3>
                <pre>{{ fs_status.stdout }}</pre>
                
                <h3>Información Red </h3>
                <pre>{{ infoNet.stdout }}</pre>

                <h3>Actualizaciones de seguridad</h3>
                <pre>{{ info_security.stdout }}</pre>

                <h3>Aplicación de actualizaciones</h3>
                <pre>{{ security_update.stdout if security_update is defined else 'No
                se aplicaron actualizaciones' }} </pre>
                <pre>
                ¿Se limpió cache?: {{ "true" if security_cache is defined else "false" }}

                {% if security_cache is defined %}
                {{ security_cache.stdout }}
                {% elif security_update is defined %}
                {{ security_update.stdout }}
                {% else %}
                No se aplicaron actualizaciones
                {% endif %}
                </pre>
                </div>

    - name: Guardar reporte temporal
      delegate_to: localhost
      lineinfile:
        path: "/tmp/informesTemporal.txt"
        create: yes
        line: "{{ reporte_host }}"
      run_once: false

    - name: Leer informes
      delegate_to: localhost
      run_once: true
      shell: cat /tmp/informesTemporal.txt
      register: archivoFinal
      changed_when: false
                
    - name: Generar informe HTML
      delegate_to: localhost
      run_once: true

      copy:
        dest: "{{ ruta_html }}"
        content: |
          <!DOCTYPE html>
          <html lang="es">
          <head>
              <meta charset="UTF-8">
              <title> Informe Diagnostico - {{ fecha_actual }}</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 20px; background: #fafafa; color: #333; }
                  h1, h2 {color: #0044cc; }
                  pre { background: #f4f4f4; padding: 10px; boder-radius: 6px; overflow-x: auto;
                  .host-block { background: #fff; padding: 15px; border-radius: 10px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
             </style>
          </head>
          <body>
              <h1>Informe Diagnostico Idiger - {{ fecha_actual }}</h1>
              {{ archivoFinal.stdout }}
          </body>
          </html>
      tags: informe
